language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_script:
  - cd docs
  - npm install -g --save firebase-tools

after_success:
  - firebase deploy --token "1/uoZsdlLIcLPHl-FQSnvjyBgh0DEFPeL2Q3o4fXtLPEjdNDhbCL9n93f7Z0Ww9TMM"
