#.travis.yml
language: generic
sudo: required
branches:
  only:
    - master
before_deploy:
  - cd docs
  - cd functions
  - rm -rf node_modules
  - npm cache clear
  - npm install
  - npm install -g --save firebase-tools
  - cd ..

deploy:
  provider: firebase
  token:
    secure: "1/uoZsdlLIcLPHl-FQSnvjyBgh0DEFPeL2Q3o4fXtLPEjdNDhbCL9n93f7Z0Ww9TMM"
  project: "winsonluk-75a4f"
