branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script: cd docs && firebase deploy --token=${1/nJI_Jm3e1EAoM3mKq2DIbu5eAaEFaN4KoDDVeasVR6c} --project winsonluk-75a4f
