language: generic
sudo: required
before_deploy: cd docs && npm install -g firebase-tools && npm install es6-promise --save

deploy:
  provider: firebase
  token:
    secure: "1/uoZsdlLIcLPHl-FQSnvjyBgh0DEFPeL2Q3o4fXtLPEjdNDhbCL9n93f7Z0Ww9TMM"
  project: "winsonluk-75a4f"
